export const sourceClaims = [
  {
    claim: "Malang City generated approximately 731.29 tonnes of waste per day in 2024, with organic waste at approximately 61%.",
    title: "98,68 Percent of Waste Generation in Malang City Successfully Managed",
    publisher: "Malang City Government",
    year: "2025",
    href: "https://www.malangkota.go.id/en/2025/02/03/9868-persen-timbulan-sampah-di-kota-malang-berhasil-dikelola/",
    supports: "Local waste scale and organic fraction.",
    status: "Verified secondary evidence",
  },
  {
    claim: "In 2025 Malang City generated approximately 800 tonnes/day; about 475 tonnes/day still entered Supit Urang landfill.",
    title: "KLH Apresiasi Langkah Kota Malang Wujudkan Pengelolaan Sampah Berkelanjutan",
    publisher: "Malang City Government",
    year: "2026",
    href: "https://malangkota.go.id/2026/05/11/klh-apresiasi-langkah-kota-malang-wujudkan-pengelolaan-sampah-berkelanjutan/",
    supports: "Need for stronger upstream sorting and integrated waste management.",
    status: "Verified secondary evidence",
  },
  {
    claim: "UMM processed institutional organic waste primarily into compost and eco-enzyme, not the proposed ORBIT energy-return loop.",
    title: "UMM Olah 92 Persen Sampah Organik Menjadi Pupuk dan Eko-Enzim Kampus",
    publisher: "Universitas Muhammadiyah Malang",
    year: "2026",
    href: "https://umm.ac.id/umm-olah-92-persen-sampah-organik-menjadi-pupuk-dan-eko-enzim-kampus/",
    supports: "Local institutional organic waste handling example.",
    status: "Verified secondary evidence",
  },
  {
    claim: "Anaerobic digestion breaks down organic matter without oxygen and produces biogas and digestate.",
    title: "How Does Anaerobic Digestion Work?",
    publisher: "US EPA AgSTAR",
    year: "2025",
    href: "https://www.epa.gov/agstar/how-does-anaerobic-digestion-work",
    supports: "AD process, biogas, digestate, and gas-use boundaries.",
    status: "Verified secondary evidence",
  },
  {
    claim: "Waste-related greenhouse-gas estimates need recognised methodology and should not be overclaimed.",
    title: "2006 IPCC Guidelines and 2019 Refinement, Volume 5 Waste",
    publisher: "IPCC",
    year: "2006/2019",
    href: "https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol5.html",
    supports: "Accepted waste GHG methodology references.",
    status: "Verified secondary evidence",
  },
  {
    claim: "Bio-CNG is outside the student MVP because compressed biomethane requires industrial processing, standards, studies, and permits.",
    title: "Pabrik BioCNG Komersial Pertama di Indonesia Diresmikan",
    publisher: "Ministry of Energy and Mineral Resources",
    year: "2024",
    href: "https://www.esdm.go.id/id/media-center/arsip-berita/pabrik-biocng-komersial-pertama-di-indonesia-diresmikan",
    supports: "Bio-CNG complexity benchmark.",
    status: "Verified secondary evidence",
  },
  {
    claim: "Biogas and biomethane equipment require Indonesian standards and specialist validation.",
    title: "SNI 7927:2023, SNI 8019:2014, SNI 9164:2023",
    publisher: "Badan Standardisasi Nasional",
    year: "2014/2023",
    href: "https://pesta.bsn.go.id/produk/by_ics?ics_no=27.190&key=",
    supports: "Safety and technical validation boundaries.",
    status: "Verified secondary evidence",
  },
];
